'use client';
import Topbar from "@/components/Topbar";

export const metadata = {
  title: 'My Job Portal',
  description: 'Generated by Next.js',
};


export default function RootLayout({ children }) {
  return (
    <>

    <html lang="en">
      <body>{children}</body>
    </html>
    </>
  );
}
