// src/app/layout.jsx

import '../../app/globals.css'; // Optional: if you’re using Tailwind or global styles

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
