<<<<<<< HEAD:src/app/user/layout.js
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
=======
import './globals.css'
>>>>>>> 05ded5a3de4fdc5f62eb526c3319400b886afad8:src/app/layout.jsx

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
